### ISSUE TITLE
13.2.0.0 generating non-working C# client with ChangeType as a culprit

### ISSUE THREAD

**Issue by HolopaMir** [RicoSuter/NSwag#2596]
Upgrading from 13.1.6.0 to 13.2.0.0 creates client, that compiles, but does not work (Can't convert from System.String).

Problem is when client is generated, it tries to serialize json to types with ChangeType:

```
var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
var result_ = (System.Collections.Generic.ICollection<string>)System.Convert.ChangeType(responseData_, typeof(System.Collections.Generic.ICollection<string>));
```

Old version does this correctly:
```
var objectResponse_ = await ReadObjectResponseAsync<System.Collections.Generic.ICollection<string>>(response_, headers_).ConfigureAwait(false);
return objectResponse_.Object;
```

Here is the bug repro for this issue: https://github.com/Enegia/NSwagGeneratorChangeTypeBugRepro

**Comment by HolopaMir** [comment]
Releates to: https://github.com/RicoSuter/NSwag/issues/1866

**Comment by pantonis** [comment]
Have the same issue here. Just upgrades and the latest upgrade causes this problem

**Comment by scberr** [comment]
I was able to work around this by adding a [Produces("application/json")] to the top of my controller definition. e.g.
```
    [Produces("application/json")]
    [Route("api/[controller]")]
    [ApiController]
    public class MyController : ControllerBase
```

**Comment by HolopaMir** [comment]
@scberr thanks, that fixed problem for us too.

We have tons of controllers, so we end up using global filter (startup.cs):

```
services.AddControllers(options =>
{
	options.Filters.Add(new ProducesAttribute("application/json"));
});
```

**Comment by RicoSuter** [comment]
Strange, i think we need to look into this regression

**Comment by aherrick** [comment]
this also broke my code. Don't have the ability to change controller endpoints. Rolled back 13.1.6.0

**Comment by RicoSuter** [comment]
Must be a regression of this PR:
https://github.com/RicoSuter/NSwag/pull/2587

@Jehoel

**Comment by Jehoel** [comment]
Erk!

I'm away from my desktop where my proper NSwag repo is - I'll be able to look at this after this coming weekend.

**Comment by RicoSuter** [comment]
I hope I fixed this in this commit:
https://github.com/RicoSuter/NSwag/commit/4fbc0ccf65750f6e5d36abb0218da0862b6b96c7

v13.2.1

**Comment by RicoSuter** [comment]
I think i only minimized the problems but when the type is text/plain then there is still a problem in some cases. Can someone create a fix PR?

**Comment by RicoSuter** [comment]
Is this still a problem?

**Comment by Jehoel** [comment]
@RicoSuter - in this issue ( https://github.com/RicoSuter/NSwag/issues/2384 ) the user @tmort93 (and 3 other +1s) are asking for an ETA on my already-merged patch.

**Comment by icnocop** [comment]
Commit 4fbc0ccf65750f6e5d36abb0218da0862b6b96c7 still causes this runtime error in the generated c# client code when my API endpoint returns content-type "application/problem+json" because `ResponseModelBase.IsPlainText` unexpectedly evaluates to `true`:
```
public bool IsPlainText =>
    !_response.Content.ContainsKey("application/json") &&
    (_response.Content.ContainsKey("text/plain") || _operationModel.Produces == "text/plain");
```

PR #3467 doesn't completely resolve this issue, but is **very** close.

I'll work on creating a pull request with a possible fix.

Thank you.

**Comment by icnocop** [comment]
Please try again with NSwag v13.12.0, as I believe it was fixed in PR https://github.com/RicoSuter/NSwag/pull/3535.

Thank you.
