### ISSUE TITLE
Operation reference in yaml file does not parse to OpenApiDocument

### ISSUE THREAD

**Issue by YoupHulsebos** [RicoSuter/NSwag#3109]
Hi,

I have an issue generating code for a yaml file. It seems the reference in the file is not handled correctly.

An sample file that fails parsing to an OpenApiDocument is:
```
swagger: '2.0'
info:
  title: foo
  version: '1.0'
paths:
  /bar:
    $ref: './otherYaml_bar.yaml'
```

On a fork I made an test that shows the error. You can find a compare with the current here: https://github.com/RicoSuter/NSwag/compare/master...YoupHulsebos:bug/pathReference

The exception given is `System.InvalidOperationException : Could not resolve the JSON path './path.yaml' within the file path '\NSwag\src\NSwag.Core.Yaml.Tests\bin\Debug\netcoreapp2.0\References\YamlReferencesTest\./path.yaml'.`

Can you help me figure out what is wrong here? It is my sample or is there something wrong in NSwag?

Kind regards,
Youp

**Comment by davidmbillie** [comment]
In your tests, you could try adding a reference header like this:

path.yaml:
`
paths:
  /bar:
    $ref: './path.yaml#/barOperation'
`

yaml_contract_path_reference.yaml:

`
barOperation:
    post:
        summary: Bar Operation
        responses:
        '200':
         ...
`

Here's some example tests for how it should be working now:
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Core.Tests/Serialization/PathItemTests.cs
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Core.Tests/Serialization/PathItemTest/PathItemWithRef.json

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Core.Tests/Serialization/ExternalReferenceTests.cs
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Core.Tests/TestFiles/path-reference.json

**Comment by YoupHulsebos** [comment]
Thanks! I tried your suggestion. However I'm still receiving an exception. Now `System.InvalidOperationException : Could not find the JSON path of a referenced schema: Manually referenced schemas must be added to the 'Definitions' of a parent schema.` 
I'm not sure what it expects me to add in my yaml file.

But shouldn't it be possible to simply use a full document as a reference? Reading the docs on [swagger.io
](https://swagger.io/docs/specification/using-ref/) under the "$ref Syntax" they specify:
`Remote Reference – $ref: 'document.json' Uses the whole document located on the same server and in the same location.`

That would suggest that I should not need the reference header. What do you think about that?

**Comment by davidmbillie** [comment]
I ran your test and looks the parsing to an OpenApiDocument is being done correctly, but then the new exception occurs in the `var json = document.ToJson();` line afterwards. Is the `.toJson()` line needed in your original tests? If so, looks like that would be an issue in NJsonSchema.

I saw the full document reference for a path item being discussed in this issue: https://github.com/RicoSuter/NSwag/issues/1880#issuecomment-478201196. I feel like it would a nice-to-have, but I don't think it would work well with how path comparisons are integrated into reference loading.

**Comment by YoupHulsebos** [comment]
Great remark on the `.toJson()` call david. You are totally correct. My goal is to generate a C# client for a yaml file with a $ref quite similar as the one in the test.

I have edited the test to show what my goal is. Right now when I add an OpenApi Service Reference in Visual studio to the yaml file in the test I get an exception on in JSON serialisation: [OpenAPi Connected Service output.txt](https://github.com/RicoSuter/NSwag/files/5407583/OpenAPi.Connected.Service.output.txt)

The suggestion in #1880 is that this is not supported at the moment. And reading your reaction it feels like its hard to support right now. 
There is a mention on the roadmap to fix loading reference definitions in NSwag v12 and NJsonSchema v10. Feels really similar. Could this be the same?
